
set(SOURCES_Src_Server_Coordinator_CoordinatorServer CoordinatorRunner.cpp CoordinatorRunner.h CoordinatorServer.cpp CoordinatorServer.h ServiceAppearanceNotifierIface.h ServiceAppearancePublisher.cpp ServiceAppearancePublisher.h ServiceAppearanceNotifySink.h CoordinatorServerNaming.h CoordinatorServiceStatus.h CoordinatorServerIface.h CoordinatorClientContext.cpp CoordinatorClientContext.h CoordinatorServerCfg.cpp CoordinatorServerCfg.h CoordinatorSvcContext.cpp CoordinatorSvcContext.h)
set(LIBRARIES_Src_Server_Coordinator_CoordinatorServer )
