
set(SOURCES_Src_Server_RdpTransport_RdpTransportBase RdpTransportBase.h RdpTransportBase.cpp RdpTransportListener.h RdpTransportListener.cpp)
set(LIBRARIES_Src_Server_RdpTransport_RdpTransportBase )
