
set(SOURCES_Src_Game_PF_Server_Accounting_BillingImpulsiveBuffsLoader BillingImpulsiveBuffsLoader.cpp BillingImpulsiveBuffsLoader.h)
set(LIBRARIES_Src_Game_PF_Server_Accounting_BillingImpulsiveBuffsLoader )
