
set(SOURCES_Src_Game_PF_Server_LobbyPvx_all LobbyIServerInstance.h LobbyIEntrance.h LobbyEntrance.cpp LobbyEntrance.h LobbyServerConnection.cpp LobbyServerConnection.h LobbyGameSession.cpp LobbyGameSession.h LobbyCustomGame.cpp LobbyCustomGame.h LobbySocialProxy.cpp LobbySocialProxy.h LobbyServerNode.cpp LobbyServerNode.h LobbySocUserPrepare.h LobbySocUserPrepare.cpp LobbyServerLoginWrapper.h LobbyServerLoginWrapper.cpp ISessionHybridLink.h SessionHybridLink.cpp SessionHybridLink.h ILoginSvcWrapper.h LobbyLog.h LobbyConfig.h LobbyConfig.cpp)
set(LIBRARIES_Src_Game_PF_Server_LobbyPvx_all )
